sonar: add logging to osci sonar targets

diff --git a/modules/sonar/Makefile b/modules/sonar/Makefile
--- a/modules/sonar/Makefile
+++ b/modules/sonar/Makefile
@@ -20,20 +20,21 @@ sonar/go: go/gosec-install
 ## Run SonarCloud analysis for Go on OpenShift CI. This will not be run during local development.
 sonar/go/openshiftci: export SONAR_TOKEN="$(shell cat /etc/sonarcloud/token 2> /dev/null)"
 sonar/go/openshiftci:
-	@echo "Verify sonar token from kube secret has been mounted"
-	@if [[ -z "${SONAR_TOKEN}" ]] ; then echo "---> ERROR: SONAR_TOKEN is not set" ; exit 1 ; fi
+	@echo "Verify sonar token from kube secret has been mounted" | tee "${ARTIFACT_DIR}/sonar.log"
+	@if [[ -z "${SONAR_TOKEN}" ]] ; then echo "---> ERROR: SONAR_TOKEN is not set" | tee "${ARTIFACT_DIR}/sonar.log" ; exit 1 ; fi
 	
-	@echo "Running go test"
+	@echo "Running go test" | tee "${ARTIFACT_DIR}/sonar.log"
 	go test -coverprofile=coverage.out -json ${SONAR_GO_TEST_ARGS} | tee report.json "${ARTIFACT_DIR}/sonar_gotest.json"
 	
-	@echo "Running gosec" 
+	@echo "Running gosec" | tee "${ARTIFACT_DIR}/sonar.log"
 	gosec -fmt sonarqube -no-fail ./... | tee gosec.json "${ARTIFACT_DIR}/sonar_gosec.json"
 	
-	@echo "Starting Sonar Scanner"
-	@echo "JOB_TYPE=${JOB_TYPE}"
-	@echo "PULL_BASE_REF=${PULL_BASE_REF}"
-	@echo "PULL_NUMBER=${PULL_NUMBER}"
-	@echo "BRANCH=$(shell curl -s "https://api.github.com/repos/${REPO_OWNER}/${REPO_OWNER}/pulls/${PULL_NUMBER}" | jq ".head.ref")"
+	@echo "Starting Sonar Scanner" | tee "${ARTIFACT_DIR}/sonar.log"
+	@echo "JOB_TYPE=${JOB_TYPE}" | tee "${ARTIFACT_DIR}/sonar.log"
+	@echo "PULL_BASE_REF=${PULL_BASE_REF}" | tee "${ARTIFACT_DIR}/sonar.log"
+	@echo "PULL_NUMBER=${PULL_NUMBER}" | tee "${ARTIFACT_DIR}/sonar.log"
+	@echo "REPO_OWNER=${REPO_OWNER}" | tee "${ARTIFACT_DIR}/sonar.log"
+	@echo "BRANCH=$(shell curl -s "https://api.github.com/repos/${REPO_OWNER}/${REPO_OWNER}/pulls/${PULL_NUMBER}" | jq ".head.ref")" | tee "${ARTIFACT_DIR}/sonar.log"
 	@if [[ "${JOB_TYPE}" == "presubmit" ]]; then \
 		echo "sonar.pullrequest.base=${PULL_BASE_REF}" >> sonar-project.properties ; \
 		echo "sonar.pullrequest.key=${PULL_NUMBER}" >> sonar-project.properties ; \
@@ -47,18 +48,18 @@ sonar/go/openshiftci:
 ## Run SonarCloud analysis for Go on OpenShift CI as a post-submit job. This will not be run during local development.
 sonar/go/openshiftci-post: export SONAR_TOKEN="$(shell cat /etc/sonarcloud/token 2> /dev/null)"
 sonar/go/openshiftci-post:
-	@echo "Verify sonar token from kube secret has been mounted"
-	@if [[ -z "${SONAR_TOKEN}" ]] ; then echo "---> ERROR: SONAR_TOKEN is not set" ; exit 1 ; fi
+	@echo "Verify sonar token from kube secret has been mounted" | tee "${ARTIFACT_DIR}/sonar.log"
+	@if [[ -z "${SONAR_TOKEN}" ]] ; then echo "---> ERROR: SONAR_TOKEN is not set" | tee "${ARTIFACT_DIR}/sonar.log"; exit 1 ; fi
 	
-	@echo "Running go test"
+	@echo "Running go test" | tee "${ARTIFACT_DIR}/sonar.log"
 	go test -coverprofile=coverage.out -json ${SONAR_GO_TEST_ARGS} | tee report.json "${ARTIFACTS}/sonar_gotest.json"
 	
-	@echo "Running gosec" 
+	@echo "Running gosec" | tee "${ARTIFACT_DIR}/sonar.log"
 	gosec -fmt sonarqube -no-fail ./... | tee gosec.json "${ARTIFACTS}/sonar_gosec.json"
 	
-	@echo "Starting Sonar Scanner"
-	@echo "JOB_TYPE=${JOB_TYPE}"
-	@echo "PULL_BASE_REF=${PULL_BASE_REF}"
+	@echo "Starting Sonar Scanner" | tee "${ARTIFACT_DIR}/sonar.log"
+	@echo "JOB_TYPE=${JOB_TYPE}" | tee "${ARTIFACT_DIR}/sonar.log"
+	@echo "PULL_BASE_REF=${PULL_BASE_REF}" | tee "${ARTIFACT_DIR}/sonar.log"
 	@if [[ "${JOB_TYPE}" == "postsubmit" ]]; then \
 		echo "sonar.branch.name=${PULL_BASE_REF}" >> sonar-project.properties ; \
 	fi
